### ISSUE TITLE
Question I saw no official java - git api, is this the most advanced library there is for java git api?

### ISSUE THREAD

**Issue by tomer-ben-david** [bit-man/SwissArmyJavaGit#21]
While I would like to use this library I'm a little reluctant as I see most changes 7 years ago is this actively developed?

**Comment by bit-man** [comment]
Hi Tomer,

currently it's not being actively developed. I'm the only contributor and can do some work here and there from time to time. 
If you want to join as a collaborator just let me know!

**Comment by tomer-ben-david** [comment]
thanks for the quick reply! i'm now doing some evaluations to which api to use (could end up using github api), so if i need to use this library and need to make updates i'll communicate with pull requests :)
THANKS!

**Comment by bit-man** [comment]
Your help is welcome. Thanks !!
